# Generated by Django 5.2 on 2025-05-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furia_chatapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotMessage',
        ),
    ]
