# Generated by Django 5.2 on 2025-05-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Furia_chatapp', '0002_delete_botmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessage',
        ),
    ]
